### PR TITLE
fix: don't overwrite transformed file contents

### LINKED ISSUE #3: HTML tags injected by other plugins are overwritten
Hi there,

Thank you for this plugin! I've been trying to use it in conjunction with `vite-plugin-pwa`.

The PWA plugin injects HTML `script` and `link` tags similar to how this MPA plugin injects the JS and CSS entry points. You can see where the PWA plugin injects [here](https://github.com/antfu/vite-plugin-pwa/blob/9cd988cfc183eaa385216f36dcf3131f342b7b9d/src/plugins/build.ts#L22) and [here](https://github.com/antfu/vite-plugin-pwa/blob/main/src/html.ts).

The problem is that this MPA plugin (`vite-plugin-mpa-plus@0.5.0`) overwrites anything injected by another plugin, thus my output html files do not have the nodes injected by the PWA plugin. If I run the PWA plugin before the MPA plugin in `vite.config.ts`, I see the same behavior unfortunately.

This is a recent break. In `vite-plugin-multiple-page@0.4.3`, the contents injected by other plugins are _not_ overwritten and it works correctly, and on looking through your recent commits it could be a result of using `emitFile` or `writeBundle`?

### PR DESCRIPTION
**Pull request by develohpanda**
Fixes https://github.com/yzydeveloper/vite-plugin-mpa-plus/issues/3

The method is quite similar to a prior commit you have, where we don't write file contents directly. Instead, we let Vite and any userland plugins that exist transform and generate the final HTML files, and on closing the bundle we move each file into it's respective new location.

I'm fairly new to rollup and plugins so please let me know if I should change or adjust something. But the root issue is a significant blocker for me, so hopefully it can get resolved soon. :)

### CODE REVIEW

File: packages/core/src/htmlFixPlugin.ts [hunk 1]
```diff
@@ -84,23 +83,32 @@ export function createHtmlFixPlugin(options: Options): Plugin {
...
+            const dirsToRemove = emittedFiles.map(emittedFile => {
+                const { newFileName: fileName, originalFileName: removeFileName } = emittedFile
+                const newFileName = path.join(root, dest, fileName)
+                const oldFileName = path.join(root, dest, removeFileName)
+                copyFile(oldFileName, newFileName)
+                const removeDir = path.join(root, dest, removeFileName.split('/').filter(Boolean)?.[0])
+                return removeDir
+            })
+
+            // use FG to make sure dir is empty https://github.com/vbenjs/vite-plugin-html/blob/841d4ef04c3cf5ff0d4339350ae336aa83aa70ed/packages/core/src/htmlPlugin.ts#L150-L161
```
Comment (develohpanda) [inline packages/core/src/htmlFixPlugin.ts:108]: Let me know if you'd like me to do this (or can be done so in a separate PR)

Comment (yzydeveloper) [reply packages/core/src/htmlFixPlugin.ts:108]: @develohpanda I think you can provide a case where pwaPlugin works with mpaPlugin

Comment (develohpanda) [reply packages/core/src/htmlFixPlugin.ts:108]: Like a playground example? Sure thing, that should be straightforward!

Comment (yzydeveloper) [reply packages/core/src/htmlFixPlugin.ts:108]: I have reproduced locally and tested your code has solved the problem

Comment (develohpanda) [reply packages/core/src/htmlFixPlugin.ts:108]: Awesome! 🤩

Comment (yzydeveloper) [reply packages/core/src/htmlFixPlugin.ts:108]: Thank you bro for finding this problem and solving it

Comment (yzydeveloper) [reply packages/core/src/htmlFixPlugin.ts:108]: Wait a few minutes and I will post a new version for your convenience

Comment (develohpanda) [reply packages/core/src/htmlFixPlugin.ts:108]: I really appreciate such a quick turn around! Thanks a lot ☺️

Comment (yzydeveloper) [reply packages/core/src/htmlFixPlugin.ts:108]: @develohpanda 我已发布vite-plugin-mpa-plus `v0.5.1` patch version

Comment (yzydeveloper) [reply packages/core/src/htmlFixPlugin.ts:108]: @develohpanda I have released vite-plugin-mpa-plus v0.5.1 patch version
